Repository hmcts/civil-wa-task-configuration, pull requests merged in 2023-08, with the labels that each got.

#313 CIV-0000 Java Logging Upgrade
  build.gradle
Labels: ns:civil, prd:civil, rel:civil-task-configuration-pr-313

#316 CIV-0000 Upgrading to java 17
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: ns:civil, prd:civil, rel:civil-task-configuration-pr-316

#314 CIV-5339 - Release 2 - LIP v LIP Update Access Profile JSON
  bin/add-roles.sh
Labels: ns:civil, prd:civil, rel:civil-task-configuration-pr-314

#317 CIV-9618 GA consent order
  src/main/resources/wa-task-initiation-civil-generalapplication.dmn
  src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmnga/CamundaGaSubmissionTaskWaInitiationTest.java
Labels: ns:civil, prd:civil, rel:civil-task-configuration-pr-317
