Repository hmcts/civil-wa-task-configuration, pull requests merged in 2023-07, with the labels that each got.

#309 CIV-9513 removed cui exclusion
  Jenkinsfile_CNP
Labels: ns:civil, prd:civil, rel:civil-task-configuration-pr-309

#308 CIV-9440 - Added Mediation Unsuccessful event in init dmn.
  src/main/resources/wa-task-initiation-civil-civil.dmn
  src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java
Labels: ns:civil, prd:civil, rel:civil-task-configuration-pr-308

#302 CIV-7897 - Update add-roles.sh
  bin/add-roles.sh
Labels: ns:civil, prd:civil, rel:civil-task-configuration-pr-302
