Repository hmcts/civil-wa-task-configuration, pull requests merged in 2023-04, with the labels that each got.

#204 CIV-TASK Temporarily suppress CVE-2023-20860
  config/owasp/suppressions.xml
Labels: ns:civil, prd:civil, rel:civil-task-configuration-pr-204

#202 CIV-7230 Enforce conventions on branch names and commit messages
  .git-config/hooks/commit-msg
  .git-config/hooks/pre-commit
  .github/workflows/main.yml
  README.md
Labels: ns:civil, prd:civil, rel:civil-task-configuration-pr-202

#205 CIV-TASK Change JDK distro
  Dockerfile
Labels: ns:civil, prd:civil, rel:civil-task-configuration-pr-205

#220 CIV-6942 changing the dmn name and specific access request names
  src/main/resources/wa-task-types-civil-generalapplication.dmn
  src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmnga/CamundaGaWaTaskTypesTest.java
Labels: ns:civil, prd:civil, rel:civil-task-configuration-pr-220

#225 CIV-0000 - Downgrade def processor version
  bin/utils/process-definition.sh
Labels: ns:civil, prd:civil, rel:civil-task-configuration-pr-225

#217 CIV-7579 Added Refert to judge and Legal Adviosr
  src/main/resources/wa-task-completion-civil-generalapplication.dmn
  src/main/resources/wa-task-configuration-civil-generalapplication.dmn
  src/main/resources/wa-task-initiation-civil-generalapplication.dmn
  src/main/resources/wa-task-permissions-civil-generalapplication.dmn
  src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmnga/CamundaGaSubmissionTaskWaInitiationTest.java
  src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmnga/CamundaGaTaskCompletion.java
  src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmnga/CamundaGaTaskWaPermissionTest.java
  src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmnga/CamundaGenAppConfigurationTest.java
Labels: ns:civil, prd:civil, rel:civil-task-configuration-pr-217

#227 CIV-0000 - def processor version to latest
  bin/utils/process-definition.sh
Labels: ns:civil, prd:civil, rel:civil-task-configuration-pr-227

#231 CIV-8009 Increase SLA to 20 Days for Non Urgent appln
  src/main/resources/wa-task-configuration-civil-generalapplication.dmn
  src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmnga/CamundaGenAppConfigurationTest.java
Labels: ns:civil, prd:civil, rel:civil-task-configuration-pr-231

#229 CIV-4923 Added configuration for bank holiday
  build.gradle
  src/main/resources/wa-task-configuration-civil-generalapplication.dmn
  src/main/resources/wa-task-initiation-civil-generalapplication.dmn
  src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmnga/CamundaGaSubmissionTaskWaInitiationTest.java
  src/test/java/uk/gov/hmcts/civil/taskconfiguration/dmnga/CamundaGenAppConfigurationTest.java
Labels: ns:civil, prd:civil, rel:civil-task-configuration-pr-229

#233 CIV-0000 Adding wa access profile
  bin/add-roles.sh
Labels: ns:civil, prd:civil, rel:civil-task-configuration-pr-233
